### PR TITLE
Set up Travis CI and Codecov integration

### PR DESCRIPTION
**Pull request by olexandr-konovalov**

### CODE REVIEW

**Comment by egri-nagy** [comment]
Thanks a lot!

**Comment by olexandr-konovalov** [comment]
Not at all @egri-nagy - you should be able to see that tests failed, so this PR should not be merged. 

They failed because digraphs failed to build - perhaps @fingolfin could advice how to fix this? I have specified 

    - GAP_PKGS_TO_BUILD="digraphs json io profiling orb semigroups"

but do I need to do anything else?

**Comment by egri-nagy** [comment]
Yes, I saw digraphs failing. I have 0.13.0 in my gap 4.10 distribution, and that one works.

**Comment by james-d-mitchell** [comment]
Is there an issue with Digraphs? Can you post a link to the failing build?

**Comment by olexandr-konovalov** [comment]
@james-d-mitchell I am not sure if this is in digraphs or some adjustment of `.travis.yml` may be needed. Link to the failing build: https://travis-ci.org/gap-packages/sgpdec/builds/504156628

**Comment by olexandr-konovalov** [comment]
@egri-nagy good to know that it works elsewhere, but for the efficient use of Travis CI we need to ensure that it works here :)

**Comment by james-d-mitchell** [comment]
Hmm, looks like maybe this is the fault of Digraphs. It looks like the compiler isn't happy that we are using C99, I think we forgot to add a flag. I'll open a PR to fix this later today if I have time.

**Comment by olexandr-konovalov** [comment]
OTOH, in the test at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/jobs/504288569 SgpDec is dropped into the Docker container for the stable-4.10 branch and recent packages - and Digraphs works there (the test fails but for another reason).

**Comment by egri-nagy** [comment]
I tested it with the 4.10.1 release, and locally on my machine everything works fine.

**Comment by olexandr-konovalov** [comment]
@egri-nagy Ok, I will submit another PR experimenting with Digraphs build options, but please do not merge it until it will begin to work.

**Pull request merged**
